config/routes.rb
Rails.application.routes.draw do

  resources :answers

  resources :proof_answereds

  resources :proof_issues

  resources :proofs

  resources :alternatives

  resources :quests

  resources :issues

  resources :subjects

  resources :disciplines

  resources :teachers
  
   resources :issues do
      resources :alternatives
   end
   
    resources :issues do
      resources :proof_issues
   end
   
   resources :disciplines do
      resources :subjects
   end
   
     resources :teachers do
      resources :disciplines
   end
   
       resources :subjects do
      resources :proofs
   end
   
         resources :proofs do
      resources :proof_issues
   end
  
  
      resources :proof_issues do
      resources :answers
   end
   
       resources :proof_answereds do
      resources  :answers
   end
   
       resources :answers do
      resources  :alternatives
   end
  resources :testa_token
  
  post 'proof_answereds/testa_token' => 'proof_answered#testa_token' 
  
   resources :relatorio

  get 'sessions/new'

  get 'users/new'
  get "dados_pessoais" => "teachers#new", :as => "dados_pessoais"
  get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "disciplinas" => "disciplines", :as => "disciplinas"
root :to => "users#index"
resources :users
resources :sessions

end

app/models/alternative.rb
class Alternative < ActiveRecord::Base
    attr_accessible :description, :correct, :issue_id
    belongs_to :issue
  
    validates_presence_of :description
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :proof_answered_id, :proof_issue_id, :alternative_id
  belongs_to :proof_answered
  belongs_to :proof_issue
  belongs_to :alternative
  
 def selecionaQuestoes
    @questoes = ProofIssue.all
 end 

end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
    attr_accessible :name, :teacher_id
    belongs_to :teacher
    has_many :subjects
    
    validates_presence_of :name
end

app/models/issue.rb
class Issue < ActiveRecord::Base
    
  attr_accessible :inunciation, :tipo, :dificulty, :subject_id
  belongs_to :subject
  has_many :alternatives

    has_many :proof_issues
    has_many :proofs, through: :proof_issues#, source: :proofs
  
  validates_presence_of :inunciation
  validates_presence_of :tipo
  validates_presence_of :dificulty
  validates_presence_of :subject_id
  
  
end

app/models/proof.rb
class Proof < ActiveRecord::Base
  
  
  
  attr_accessible :message, :header,:token, :closingDate, :duration,:status, :questionsNumber, :subject_id, :teacher_id

  belongs_to :subject
  belongs_to :teacher

  has_many :proof_issues
  has_many :issues, through: :proof_issues
  
  validates_uniqueness_of :token

  #has_and_belongs_to_many :issues

  # has_many :proof_issues, :dependent => :destroy


  validates_presence_of :message
  validates_presence_of :token
  validates_presence_of :status
  validates_presence_of :questionsNumber
  validates_presence_of :subject_id

 def self.testa_token?(token)
    valido = Proof.where(token: token).first()
    
    if valido
      true
    else
      false
    end
  end
  
  def self.get_proof_id(token)
    Proof.where(token: token).first().id
  end
  
end

app/models/proof_answered.rb
class ProofAnswered < ActiveRecord::Base
      attr_accessible :name, :email,:endTime, :startTime, :token, :answers_attributes
      has_many :answers
      has_many :proof_issues, through: :answers
      accepts_nested_attributes_for :answers, :reject_if => :all_blank, :allow_destroy => true
      validates_presence_of :name
      validates_presence_of :email
      validates_presence_of :token
      
      validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
      
end

app/models/proof_issue.rb
class ProofIssue < ActiveRecord::Base
 
 attr_accessible :issue_id, :proof_id

  belongs_to :issue
  belongs_to :proof
  has_many :answers
  has_many :proof_answereds, through: :answers#, source: :proofs


  
end

app/models/quest.rb
class Quest < ActiveRecord::Base
  belongs_to :discipline
  belongs_to :subject
  belongs_to :teacher
end

app/models/subject.rb
class Subject < ActiveRecord::Base
    attr_accessible :name, :discipline_id
  belongs_to :discipline
  has_many :issues
  has_many :proofs
  
  validates_presence_of :name
  validates_presence_of :discipline_id

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
    attr_accessible :name, :cpf, :date, :phone, :user_id
  belongs_to :user
  has_many :disciplines
  has_many :proofs
  
  validates_presence_of :name
  validates_presence_of :cpf
  validates_presence_of :date
  validates_presence_of :phone
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :teacher
      attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/proof_issues_controller.rb
class ProofIssuesController < ApplicationController
  before_action :set_proof_issue, only: [:show, :edit, :update, :destroy]



  def mostraQuestoes(token)
    
  

  end
  # GET /proof_issues
  # GET /proof_issues.json
  def index
   
    @proof_issues = ProofIssue.all
  end

  # GET /proof_issues/1
  # GET /proof_issues/1.json
  def show
  end

  # GET /proof_issues/new
  def new
    @proof_issue = ProofIssue.new
  end

  # GET /proof_issues/1/edit
  def edit
  end

  # POST /proof_issues
  # POST /proof_issues.json
  def create
    @proof_issue = ProofIssue.new(proof_issue_params)

    respond_to do |format|
      if @proof_issue.save
        format.html { redirect_to @proof_issue, notice: 'Proof issue was successfully created.' }
        format.json { render :show, status: :created, location: @proof_issue }
      else
        format.html { render :new }
        format.json { render json: @proof_issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proof_issues/1
  # PATCH/PUT /proof_issues/1.json
  def update
    respond_to do |format|
      if @proof_issue.update(proof_issue_params)
        format.html { redirect_to @proof_issue, notice: 'Proof issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @proof_issue }
      else
        format.html { render :edit }
        format.json { render json: @proof_issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proof_issues/1
  # DELETE /proof_issues/1.json
  def destroy
    @proof_issue.destroy
    respond_to do |format|
      format.html { redirect_to proof_issues_url, notice: 'Proof issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proof_issue
      @proof_issue = ProofIssue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proof_issue_params
      params.require(:proof_issue).permit(:proof_id, :issue_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/proof_issues_helper.rb
module ProofIssuesHelper
end

app/helpers/proofs_helper.rb
module ProofsHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/helpers/relatorio_helper.rb
module RelatorioHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/proof_issues/_form.html.erb
<%= form_for(@proof_issue) do |f| %>
  <% if @proof_issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proof_issue.errors.count, "error") %> prohibited this proof_issue from being saved:</h2>

      <ul>
      <% @proof_issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :proof_id %><br>
    <%= f.text_field :proof_id %>
  </div>
  <div class="field">
    <%= f.label :issue_id %><br>
    <%= f.text_field :issue_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proof_issues/edit.html.erb
<h1>Editing proof_issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @proof_issue %> |
<%= link_to 'Back', proof_issues_path %>

app/views/proof_issues/index.html.erb
<h1>Listing proof_issues</h1>

<table>
  <thead>
    <tr>
      <th>Proof</th>
      <th>Issue</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% #@proof_issues.each do |proof_issue| %>
        <% @questoesProva.each do |proof_issue| %>
      <tr>
        <td><%= proof_issue.proof.id %></td>
        <td><%= proof_issue.issue.inunciation %></td>
          <% proof_issue.issue.alternatives.each do |alternativas| %>
            <td><%= alternativas.description %></td>
           <% end %>
        <td><%= link_to 'Show', proof_issue %></td>
        <td><%= link_to 'Edit', edit_proof_issue_path(proof_issue) %></td>
        <td><%= link_to 'Destroy', proof_issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proof issue', new_proof_issue_path %>

app/views/proof_issues/new.html.erb
<h1>New proof_issue</h1>

<%= render 'form' %>

<%= link_to 'Back', proof_issues_path %>

app/views/proof_issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Proof:</strong>
  <%= @proof_issue.proof %>
</p>

<p>
  <strong>Issue:</strong>
  <%= @proof_issue.issue %>
</p>

<%= link_to 'Edit', edit_proof_issue_path(@proof_issue) %> |
<%= link_to 'Back', proof_issues_path %>