config/routes.rb
Rails.application.routes.draw do

  resources :answers

  resources :proof_answereds

  resources :proof_issues

  resources :proofs

  resources :alternatives

  resources :quests

  resources :issues

  resources :subjects

  resources :disciplines

  resources :teachers
  
   resources :issues do
      resources :alternatives
   end
   
    resources :issues do
      resources :proof_issues
   end
   
   resources :disciplines do
      resources :subjects
   end
   
     resources :teachers do
      resources :disciplines
   end
   
       resources :subjects do
      resources :proofs
   end
   
         resources :proofs do
      resources :proof_issues
   end
  
  
      resources :proof_issues do
      resources :answers
   end
   
       resources :proof_answereds do
      resources  :answers
   end
   
       resources :answers do
      resources  :alternatives
   end
  resources :testa_token
  
  post 'proof_answereds/testa_token' => 'proof_answered#testa_token' 
  
   resources :relatorio

  get 'sessions/new'

  get 'users/new'
  get "dados_pessoais" => "teachers#new", :as => "dados_pessoais"
  get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "disciplinas" => "disciplines", :as => "disciplinas"
root :to => "users#index"
resources :users
resources :sessions

end

app/models/alternative.rb
class Alternative < ActiveRecord::Base
    attr_accessible :description, :correct, :issue_id
    belongs_to :issue
  
    validates_presence_of :description
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :proof_answered_id, :proof_issue_id, :alternative_id
  belongs_to :proof_answered
  belongs_to :proof_issue
  belongs_to :alternative
  
 def selecionaQuestoes
    @questoes = ProofIssue.all
 end 

end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
    attr_accessible :name, :teacher_id
    belongs_to :teacher
    has_many :subjects
    
    validates_presence_of :name
end

app/models/issue.rb
class Issue < ActiveRecord::Base
    
  attr_accessible :inunciation, :tipo, :dificulty, :subject_id
  belongs_to :subject
  has_many :alternatives

    has_many :proof_issues
    has_many :proofs, through: :proof_issues#, source: :proofs
  
  validates_presence_of :inunciation
  validates_presence_of :tipo
  validates_presence_of :dificulty
  validates_presence_of :subject_id
  
  
end

app/models/proof.rb
class Proof < ActiveRecord::Base
  
  
  
  attr_accessible :message, :header,:token, :closingDate, :duration,:status, :questionsNumber, :subject_id, :teacher_id

  belongs_to :subject
  belongs_to :teacher

  has_many :proof_issues
  has_many :issues, through: :proof_issues
  
  validates_uniqueness_of :token

  #has_and_belongs_to_many :issues

  # has_many :proof_issues, :dependent => :destroy


  validates_presence_of :message
  validates_presence_of :token
  validates_presence_of :status
  validates_presence_of :questionsNumber
  validates_presence_of :subject_id

 def self.testa_token?(token)
    valido = Proof.where(token: token).first()
    
    if valido
      true
    else
      false
    end
  end
  
  def self.get_proof_id(token)
    Proof.where(token: token).first().id
  end
  
end

app/models/proof_answered.rb
class ProofAnswered < ActiveRecord::Base
      attr_accessible :name, :email,:endTime, :startTime, :token, :answers_attributes
      has_many :answers
      has_many :proof_issues, through: :answers
      accepts_nested_attributes_for :answers, :reject_if => :all_blank, :allow_destroy => true
      validates_presence_of :name
      validates_presence_of :email
      validates_presence_of :token
      
      validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
      
end

app/models/proof_issue.rb
class ProofIssue < ActiveRecord::Base
 
 attr_accessible :issue_id, :proof_id

  belongs_to :issue
  belongs_to :proof
  has_many :answers
  has_many :proof_answereds, through: :answers#, source: :proofs


  
end

app/models/quest.rb
class Quest < ActiveRecord::Base
  belongs_to :discipline
  belongs_to :subject
  belongs_to :teacher
end

app/models/subject.rb
class Subject < ActiveRecord::Base
    attr_accessible :name, :discipline_id
  belongs_to :discipline
  has_many :issues
  has_many :proofs
  
  validates_presence_of :name
  validates_presence_of :discipline_id

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
    attr_accessible :name, :cpf, :date, :phone, :user_id
  belongs_to :user
  has_many :disciplines
  has_many :proofs
  
  validates_presence_of :name
  validates_presence_of :cpf
  validates_presence_of :date
  validates_presence_of :phone
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :teacher
      attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
   
    @answers = Answer.all
     
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
        @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end
  
  
  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:proof_answered_id, :proof_issue_id, :alternative_id)
    end
    
    def destroySessao
        session[:aluno_id] = nil
        session[:token] = nil
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/proofs_helper.rb
module ProofsHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/helpers/relatorio_helper.rb
module RelatorioHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

<% @questoesProva.each do |proof_issue| %>
  <tr>
    <br>
       <td><strong><%= proof_issue.issue.inunciation %></td></strong>
  </tr><br>
  <% ###Inserido por Carlos Eduardo Egito %>
  <%#= form_for (@answers[proof_issue.issue.id] || Answer.new) do |f| %>
        <%# question.answers.each do |ans| %>
          <%#= f.radio_button :answer, ans.id %>
          <%#= f.label( ('answer_' << ans.id).to_sym, ans.text ) %>
          <%# end %>
  <%########%>
  
  <% proof_issue.issue.alternatives.each do |alternativa| %>
     <tr>
   
         <td><%= f.radio_button(:alternative_id, alternativa.id)%> <%=alternativa.description %></td><br>
         <%= f.hidden_field :proof_answered_id, :value=>current_aluno.id %>
         <%= f.hidden_field :proof_issue_id, :value=>proof_issue.id %>
      </tr>
  <% end %>
 <% end %>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      
      <th>Proof issue</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>
<% count = 0%>
<%= form_for(@answer) do |f| %>
  <% @questoesProva.each do |proof_issue| %>
  <%coutnt = count+ 1%>
  <tr>
       
        <td><strong><%= proof_issue.issue.inunciation %></td></strong>
        </tr><br>
       

    <% proof_issue.issue.alternatives.each do |alternativa| %>
     <tr>
   <td><%= f.radio_button_tag(:alternative_id, "alternativa.id")%> <%=alternativa.description %></td>
   <%= f.hidden_field :proof_answered_id, :value=>current_aluno.id %>
   <%= f.hidden_field :proof_issue_id, :value=>proof_issue.id %>
       
     
       </tr>
        <%end%>
  <%end%>
   <div class="actions">
    <%= f.submit %>
  </div>
   <%end%>

  <tbody>

  </tbody>
</table>

<br>

<%#= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/selecionaQuestoes.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      <th>Proof answered</th>
      <th>Proof issue</th>
      <th>Alternative</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questoes.each do |teste| %>
      <tr>
        <td><%= teste.id %></td>
       
    
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Proof answered:</strong>
  <%= @answer.proof_answered %>
</p>

<p>
  <strong>Proof issue:</strong>
  <%= @answer.proof_issue %>
</p>

<p>
  <strong>Alternative:</strong>
  <%= @answer.alternative %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>