config/routes.rb
Rails.application.routes.draw do

  resources :answers

  resources :proof_answereds

  resources :proof_issues

  resources :proofs

  resources :alternatives

  resources :quests

  resources :issues

  resources :subjects

  resources :disciplines

  resources :teachers
  
   resources :issues do
      resources :alternatives
   end
   
    resources :issues do
      resources :proof_issues
   end
   
   resources :disciplines do
      resources :subjects
   end
   
     resources :teachers do
      resources :disciplines
   end
   
       resources :subjects do
      resources :proofs
   end
   
         resources :proofs do
      resources :proof_issues
   end
  
  
      resources :proof_issues do
      resources :answers
   end
   
       resources :proof_answereds do
      resources  :answers
   end
   
       resources :answers do
      resources  :alternatives
   end
  resources :testa_token
  
  post 'proof_answereds/testa_token' => 'proof_answered#testa_token' 
  
   resources :relatorio

  get 'sessions/new'

  get 'users/new'
  get "dados_pessoais" => "teachers#new", :as => "dados_pessoais"
  get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
get "disciplinas" => "disciplines", :as => "disciplinas"
root :to => "users#index"
resources :users
resources :sessions

end

app/models/alternative.rb
class Alternative < ActiveRecord::Base
    attr_accessible :description, :correct, :issue_id
    belongs_to :issue
  
    validates_presence_of :description
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :proof_answered_id, :proof_issue_id, :alternative_id
  belongs_to :proof_answered
  belongs_to :proof_issue
  belongs_to :alternative
  
 def selecionaQuestoes
    @questoes = ProofIssue.all
 end 

end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
    attr_accessible :name, :teacher_id
    belongs_to :teacher
    has_many :subjects
    
    validates_presence_of :name
end

app/models/issue.rb
class Issue < ActiveRecord::Base
    
  attr_accessible :inunciation, :tipo, :dificulty, :subject_id
  belongs_to :subject
  has_many :alternatives

    has_many :proof_issues
    has_many :proofs, through: :proof_issues#, source: :proofs
  
  validates_presence_of :inunciation
  validates_presence_of :tipo
  validates_presence_of :dificulty
  validates_presence_of :subject_id
  
  
end

app/models/proof.rb
class Proof < ActiveRecord::Base
  
  
  
  attr_accessible :message, :header,:token, :closingDate, :duration,:status, :questionsNumber, :subject_id, :teacher_id

  belongs_to :subject
  belongs_to :teacher

  has_many :proof_issues
  has_many :issues, through: :proof_issues
  
  validates_uniqueness_of :token

  #has_and_belongs_to_many :issues

  # has_many :proof_issues, :dependent => :destroy


  validates_presence_of :message
  validates_presence_of :token
  validates_presence_of :status
  validates_presence_of :questionsNumber
  validates_presence_of :subject_id

 def self.testa_token?(token)
    valido = Proof.where(token: token).first()
    
    if valido
      true
    else
      false
    end
  end
  
  def self.get_proof_id(token)
    Proof.where(token: token).first().id
  end
  
end

app/models/proof_answered.rb
class ProofAnswered < ActiveRecord::Base
      attr_accessible :name, :email,:endTime, :startTime, :token, :answers_attributes
      has_many :answers
      has_many :proof_issues, through: :answers
      accepts_nested_attributes_for :answers, :reject_if => :all_blank, :allow_destroy => true
      validates_presence_of :name
      validates_presence_of :email
      validates_presence_of :token
      
      validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
      
end

app/models/proof_issue.rb
class ProofIssue < ActiveRecord::Base
 
 attr_accessible :issue_id, :proof_id

  belongs_to :issue
  belongs_to :proof
  has_many :answers
  has_many :proof_answereds, through: :answers#, source: :proofs


  
end

app/models/quest.rb
class Quest < ActiveRecord::Base
  belongs_to :discipline
  belongs_to :subject
  belongs_to :teacher
end

app/models/subject.rb
class Subject < ActiveRecord::Base
    attr_accessible :name, :discipline_id
  belongs_to :discipline
  has_many :issues
  has_many :proofs
  
  validates_presence_of :name
  validates_presence_of :discipline_id

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
    attr_accessible :name, :cpf, :date, :phone, :user_id
  belongs_to :user
  has_many :disciplines
  has_many :proofs
  
  validates_presence_of :name
  validates_presence_of :cpf
  validates_presence_of :date
  validates_presence_of :phone
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :teacher
      attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :cpf, :date, :phone, :user_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/proofs_helper.rb
module ProofsHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/helpers/relatorio_helper.rb
module RelatorioHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/teachers/_form.html.erb
<%= form_for @teacher, :html => { :class => "form-horizontal teacher" } do |f| %>

    <% if @teacher.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @teacher.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@teacher[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :cpf, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cpf, :class => 'form-control' %>
    </div>
    <%= error_span(@teacher[:cpf]) %>
  </div>
  <div class="control-group">
    <%= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :date, :class => 'form-control' %>
    </div>
    <%= error_span(@teacher[:date]) %>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%= error_span(@teacher[:phone]) %>
  </div>
  <div class="control-group">
  <%= f.hidden_field :user_id, :value=>current_user.id %>
    <%= error_span(@teacher[:user_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            teachers_path, :class => 'btn btn-default' %>

<% end %>

app/views/teachers/edit.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/teachers/index.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:cpf) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      
     
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @teachers.each do |teacher| %>
     <% if teacher.user == current_user %>
      <tr>
        <td><%= link_to teacher.id, teacher_path(teacher) %></td>
        <td><%= teacher.name %></td>
        <td><%= teacher.cpf %></td>
        <td><%= teacher.date %></td>
        <td><%= teacher.phone %></td>
        
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_teacher_path(teacher), :class => 'btn btn-default btn-xs' %>
          <%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
                     # teacher_path(teacher),
                     # :method => :delete,
                     # :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      #:class => 'btn btn-xs btn-danger' %>
        </td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/teachers/new.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%#=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %> Preencha seus dados:</h1>
</div>
<%= render :partial => 'form' %>

app/views/teachers/show.html.erb
<%- model_class = Teacher -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @teacher.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cpf) %>:</strong></dt>
  <dd><%= @teacher.cpf %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @teacher.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @teacher.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @teacher.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              teachers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_teacher_path(@teacher), :class => 'btn btn-default' %>
<%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
              teacher_path(@teacher),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>